#!/bin/bash
# Font Subsetting Script
# Generated by subset-fonts.ts

set -e

echo "Subsetting OpenDyslexic fonts..."

# Subset OpenDyslexic-Regular.woff
pyftsubset "/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Regular.woff" \
  --unicodes="U+0041-005A,U+0061-007A,U+0030-0039,U+00C6,U+00D8,U+00C5,U+00E6,U+00F8,U+00E5,U+002B,U+002D,U+00D7,U+00F7,U+003D,U+003C,U+003E,U+00B1,U+00D7,U+00F7,U+221A,U+221E,U+2260,U+2264,U+2265,U+0020-002F,U+003A-0040,U+005B-0060,U+007B-007E,U+00BC-00BE,U+2153-215E" \
  --flavor=woff2 \
  --output-file="/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Regular.subset.woff2" \
  --layout-features="*" \
  --no-hinting

# Subset OpenDyslexic-Bold.woff
pyftsubset "/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Bold.woff" \
  --unicodes="U+0041-005A,U+0061-007A,U+0030-0039,U+00C6,U+00D8,U+00C5,U+00E6,U+00F8,U+00E5,U+002B,U+002D,U+00D7,U+00F7,U+003D,U+003C,U+003E,U+00B1,U+00D7,U+00F7,U+221A,U+221E,U+2260,U+2264,U+2265,U+0020-002F,U+003A-0040,U+005B-0060,U+007B-007E,U+00BC-00BE,U+2153-215E" \
  --flavor=woff2 \
  --output-file="/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Bold.subset.woff2" \
  --layout-features="*" \
  --no-hinting

# Subset OpenDyslexic-Italic.woff
pyftsubset "/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Italic.woff" \
  --unicodes="U+0041-005A,U+0061-007A,U+0030-0039,U+00C6,U+00D8,U+00C5,U+00E6,U+00F8,U+00E5,U+002B,U+002D,U+00D7,U+00F7,U+003D,U+003C,U+003E,U+00B1,U+00D7,U+00F7,U+221A,U+221E,U+2260,U+2264,U+2265,U+0020-002F,U+003A-0040,U+005B-0060,U+007B-007E,U+00BC-00BE,U+2153-215E" \
  --flavor=woff2 \
  --output-file="/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-Italic.subset.woff2" \
  --layout-features="*" \
  --no-hinting

# Subset OpenDyslexic-BoldItalic.woff
pyftsubset "/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-BoldItalic.woff" \
  --unicodes="U+0041-005A,U+0061-007A,U+0030-0039,U+00C6,U+00D8,U+00C5,U+00E6,U+00F8,U+00E5,U+002B,U+002D,U+00D7,U+00F7,U+003D,U+003C,U+003E,U+00B1,U+00D7,U+00F7,U+221A,U+221E,U+2260,U+2264,U+2265,U+0020-002F,U+003A-0040,U+005B-0060,U+007B-007E,U+00BC-00BE,U+2153-215E" \
  --flavor=woff2 \
  --output-file="/home/dev/GitHub/edbpede/math/public/fonts/opendyslexic/OpenDyslexic-BoldItalic.subset.woff2" \
  --layout-features="*" \
  --no-hinting


echo "✅ Font subsetting complete!"
echo "Subsetted fonts saved with .subset.woff2 extension"